# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\roptions.proto\"D\n\x04YOLO\x12\x0f\n\x07\x63lasses\x18\x01 \x01(\t\x12\x0f\n\x07weights\x18\x02 \x01(\t\x12\x0c\n\x04tiny\x18\x03 \x01(\x08\x12\x0c\n\x04size\x18\x04 \x01(\r\"\xad\x02\n\rDrawingParams\x12\x12\n\nshow_boxes\x18\x01 \x01(\x08\x12\x12\n\nshow_paths\x18\x02 \x01(\x08\x12\x10\n\x08show_ids\x18\x03 \x01(\x08\x12\x12\n\nshow_names\x18\x04 \x01(\x08\x12\x13\n\x0bshow_scores\x18\x05 \x01(\x08\x12\x11\n\tbox_color\x18\x06 \x03(\r\x12\x19\n\x11missing_box_color\x18\x07 \x03(\r\x12\x12\n\npath_color\x18\x08 \x03(\r\x12\x10\n\x08id_color\x18\t \x03(\r\x12\x12\n\nname_color\x18\n \x03(\r\x12\x15\n\rbox_thickness\x18\x0b \x01(\r\x12\x16\n\x0epath_thickness\x18\x0c \x01(\r\x12\x0f\n\x07id_size\x18\r \x01(\r\x12\x11\n\tname_size\x18\x0e \x01(\r\"0\n\x0cKalmanParams\x12\t\n\x01R\x18\x01 \x01(\x02\x12\t\n\x01Q\x18\x02 \x01(\x02\x12\n\n\x02\x64t\x18\x03 \x01(\x02\"D\n\x08\x43ommands\x12\x13\n\x0buntrack_all\x18\x01 \x01(\x08\x12\x15\n\rreset_tracker\x18\x02 \x01(\x08\x12\x0c\n\x04stop\x18\x03 \x01(\x08\"u\n\x0eTrackerOptions\x12\x0e\n\x06\x66ilter\x18\x01 \x03(\t\x12\x1a\n\x12max_missing_frames\x18\x02 \x01(\r\x12\x12\n\nmax_radius\x18\x03 \x01(\r\x12#\n\x0cKalmanParams\x18\x04 \x01(\x0b\x32\r.KalmanParams\"\xda\x01\n\x07Options\x12\x0e\n\x06\x62roker\x18\x01 \x01(\t\x12\x15\n\rconsume_topic\x18\x02 \x01(\t\x12\x15\n\rpublish_topic\x18\x03 \x01(\t\x12\x13\n\x04YOLO\x18\x04 \x01(\x0b\x32\x05.YOLO\x12%\n\rDrawingParams\x18\x05 \x01(\x0b\x32\x0e.DrawingParams\x12\'\n\x0eTrackerOptions\x18\x06 \x01(\x0b\x32\x0f.TrackerOptions\x12\x1b\n\x08\x43ommands\x18\x07 \x01(\x0b\x32\t.Commands\x12\x0f\n\x07verbose\x18\x08 \x01(\x08\x62\x06proto3'
)




_YOLO = _descriptor.Descriptor(
  name='YOLO',
  full_name='YOLO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='classes', full_name='YOLO.classes', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='YOLO.weights', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiny', full_name='YOLO.tiny', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='YOLO.size', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=85,
)


_DRAWINGPARAMS = _descriptor.Descriptor(
  name='DrawingParams',
  full_name='DrawingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='show_boxes', full_name='DrawingParams.show_boxes', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='show_paths', full_name='DrawingParams.show_paths', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='show_ids', full_name='DrawingParams.show_ids', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='show_names', full_name='DrawingParams.show_names', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='show_scores', full_name='DrawingParams.show_scores', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box_color', full_name='DrawingParams.box_color', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='missing_box_color', full_name='DrawingParams.missing_box_color', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path_color', full_name='DrawingParams.path_color', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_color', full_name='DrawingParams.id_color', index=8,
      number=9, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name_color', full_name='DrawingParams.name_color', index=9,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box_thickness', full_name='DrawingParams.box_thickness', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path_thickness', full_name='DrawingParams.path_thickness', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_size', full_name='DrawingParams.id_size', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name_size', full_name='DrawingParams.name_size', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=389,
)


_KALMANPARAMS = _descriptor.Descriptor(
  name='KalmanParams',
  full_name='KalmanParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='R', full_name='KalmanParams.R', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Q', full_name='KalmanParams.Q', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dt', full_name='KalmanParams.dt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=439,
)


_COMMANDS = _descriptor.Descriptor(
  name='Commands',
  full_name='Commands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='untrack_all', full_name='Commands.untrack_all', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reset_tracker', full_name='Commands.reset_tracker', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop', full_name='Commands.stop', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=509,
)


_TRACKEROPTIONS = _descriptor.Descriptor(
  name='TrackerOptions',
  full_name='TrackerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='TrackerOptions.filter', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_missing_frames', full_name='TrackerOptions.max_missing_frames', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_radius', full_name='TrackerOptions.max_radius', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KalmanParams', full_name='TrackerOptions.KalmanParams', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=628,
)


_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker', full_name='Options.broker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consume_topic', full_name='Options.consume_topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publish_topic', full_name='Options.publish_topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='YOLO', full_name='Options.YOLO', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DrawingParams', full_name='Options.DrawingParams', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TrackerOptions', full_name='Options.TrackerOptions', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Commands', full_name='Options.Commands', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='Options.verbose', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=849,
)

_TRACKEROPTIONS.fields_by_name['KalmanParams'].message_type = _KALMANPARAMS
_OPTIONS.fields_by_name['YOLO'].message_type = _YOLO
_OPTIONS.fields_by_name['DrawingParams'].message_type = _DRAWINGPARAMS
_OPTIONS.fields_by_name['TrackerOptions'].message_type = _TRACKEROPTIONS
_OPTIONS.fields_by_name['Commands'].message_type = _COMMANDS
DESCRIPTOR.message_types_by_name['YOLO'] = _YOLO
DESCRIPTOR.message_types_by_name['DrawingParams'] = _DRAWINGPARAMS
DESCRIPTOR.message_types_by_name['KalmanParams'] = _KALMANPARAMS
DESCRIPTOR.message_types_by_name['Commands'] = _COMMANDS
DESCRIPTOR.message_types_by_name['TrackerOptions'] = _TRACKEROPTIONS
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

YOLO = _reflection.GeneratedProtocolMessageType('YOLO', (_message.Message,), {
  'DESCRIPTOR' : _YOLO,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:YOLO)
  })
_sym_db.RegisterMessage(YOLO)

DrawingParams = _reflection.GeneratedProtocolMessageType('DrawingParams', (_message.Message,), {
  'DESCRIPTOR' : _DRAWINGPARAMS,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:DrawingParams)
  })
_sym_db.RegisterMessage(DrawingParams)

KalmanParams = _reflection.GeneratedProtocolMessageType('KalmanParams', (_message.Message,), {
  'DESCRIPTOR' : _KALMANPARAMS,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:KalmanParams)
  })
_sym_db.RegisterMessage(KalmanParams)

Commands = _reflection.GeneratedProtocolMessageType('Commands', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDS,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:Commands)
  })
_sym_db.RegisterMessage(Commands)

TrackerOptions = _reflection.GeneratedProtocolMessageType('TrackerOptions', (_message.Message,), {
  'DESCRIPTOR' : _TRACKEROPTIONS,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:TrackerOptions)
  })
_sym_db.RegisterMessage(TrackerOptions)

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONS,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:Options)
  })
_sym_db.RegisterMessage(Options)


# @@protoc_insertion_point(module_scope)
